### ISSUE TITLE
Support for plugin LoginLdap (plain pass or arbitrary token)

### ISSUE THREAD

**Issue by lolllpop** [matomo-org/matomo-mobile-2#5326]
Support for the plugin LoginLdap which allows to keep the piwik DB free of user passwords. Authentication can be done against an external LDAP server, token IDs can be randomly generated.

The Mobile App would need to transmit the plain password (over TLS, of course) so that LoginLdap can use it for authentication against the LDAP server, or would need to allow for entering an arbitrary token ID which is not necessarily derived from login/pass.

As reference: https://github.com/piwik/plugin-LoginLdap/issues/79

**Comment by tsteur** [comment]
We discussed this problem a few months ago and it is not really a problem in Piwik Mobile. The proper solution for this will be piwik/piwik#6559 or maybe a bit less proper solution to allow in LoginLdap plugin to create users in Piwik DB as well that can be used for Piwik Mobile

**Comment by tsteur** [comment]
Actually I reopen this issue as we could change this behavior with Piwik 3.0 and Piwik Mobile 3.0 as this will allow us to make breaking changes (sending password in plain text). I presume in Piwik Mobile 3.0 we will only allow Piwik 3.0 installations

**Comment by dnauck** [comment]
Why not simply using the API key? Btw, any news on this topic?

**Comment by tsteur** [comment]
Hi there, this has finally been fixed in https://github.com/matomo-org/matomo-mobile-2/pull/5407 and https://github.com/matomo-org/matomo-mobile-2/pull/5406 and should be available in the next release (maybe next week). You should then be able to log in using the API token. Ideally I recommend using it together with the upcoming 3.13.6 release.
