### ISSUE TITLE
Can't access Piwik accounts that have 2FA enabled

### ISSUE THREAD

**Issue by MagicFab** [matomo-org/matomo-mobile-2#5351]
When this plugin is installed and 2FA is enabled for an account, the application simply returns an authentication error:
https://github.com/sgiehl/piwik-plugin-GoogleAuthenticator

One way would be to [implement OAuth](https://github.com/piwik/piwik/issues/906), another to implement app-specific passwords in the 2FA plugin. IANASE (I'm not a security expert!), just bringing attention to this issue when 2FA is enabled.

Piwik's / PIwik Mobile's FAQ could highlight this and suggest to use a separate account dedicated for mobile use, for viewing only (the most probable use case on mobile).

**Comment by tsteur** [comment]
FYI: This kinda depends on https://github.com/piwik/piwik/issues/6559 which I created about a year ago. I don't see it implemented soon though

**Comment by tsteur** [comment]
I think this is implemented by now and supports Matomo core 2FA feature 👍
