### ISSUE TITLE
SSL implementation vulnerability

### ISSUE THREAD

**Issue by monizb** [matomo-org/matomo-mobile-2#5401]
<SSL_Security> SSL Implementation Checking (Verifying Host Name in Custom Classes):

This app allows Self-defined HOSTNAME VERIFIER to accept all Common Names(CN).
This is a critical vulnerability and allows attackers to do MITM attacks with his valid certificate without your knowledge.

Case example:

http://www.pwntester.com/blog/2012/11/05/fourgoats-vulnerabilities-promiscuous-ssl-hostname-verifier/

Google doc: http://developer.android.com/training/articles/security-ssl.html (Caution: Replacing HostnameVerifier can be very dangerous).

OWASP Mobile Top 10 doc: https://www.owasp.org/index.php/Mobile_Top_10_2014-M3
Check this book to see how to solve this issue: http://goo.gl/BFb65r

Vulnerable Code:
Lti/modules/titanium/network/httpurlconnection/NullHostNameVerifier;->verify(Ljava/lang/String; Ljavax/net/ssl/SSLSession;)Z

Impact
If the attacker has a legit certificate signed by any trusted CA (in the Android KeyStore) for our own domain, we will be able to use it to perform a man-in-the-middle attack since the SSL TrustManager will trust the certificate as it is signed by a trusted CA but then it will fail to verify that the certificate was issued for the server we are connecting to.

To see what's the importance of Common Name(CN) verification.
Use Google Chrome to navigate:
- https://www.google.com => SSL certificate is valid
- https://60.199.175.158/ => This is the IP address of google.com, but the CN is not match, making the certificate invalid. You
still can go Google.com but now you cannot distinguish attackers from normal users

==========Via Hackerone===========
Recommended by : @mattab

**Comment by tsteur** [comment]
We have it in the iOS version as a feature as some users do use self signed certificates and can otherwise not access it. It is not enabled by default.
