### ISSUE TITLE
Login by email + password

### ISSUE THREAD

**Issue by jeantil** [matomo-org/matomo-mobile-2#5404]
It took me multiple attempts and some puzzling before I figured that only login by username was supported by the mobile app. I usually login using email/password on our matomo instance at matomo.cloud ... 

It would be really nice if the mobile app supported it too ...

**Comment by tsteur** [comment]
Created https://github.com/matomo-org/matomo/pull/15371 to support it. It'll be either in 3.13.1 or in Matomo 4.

**Comment by tsteur** [comment]
Cheers for creating the issue 👍

**Comment by jeantil** [comment]
Thanks for considering it !

Le ven. 10 janv. 2020 à 07:38, Thomas Steur <notifications@github.com> a
écrit :
