### ISSUE TITLE
Matomo plugin requirements

### ISSUE THREAD

**Issue by MichaIng** [matomo-org/matomo-mobile-2#5409]
It would be great to list the required Matomo plugins right in the apps description. I just recognised that the app uses `ImageGraph` to render it's graphs, something that is not required for the graphs in the web UI.

GeoIP setup and UserCountryMap is probably obvious enough to support the real-time map, but that is not something I need anyway 😉.

**Comment by tsteur** [comment]
Cheers @MichaIng updated it on Google Play and will need to update it on iTunes eventually 👍

**Comment by tsteur** [comment]
I have added this information to our iOS app store listing but it will only become active with another release.

Also added a note that it won't work with Matomo for WordPress

**Comment by MichaIng** [comment]
Found it in PlayStore, LGTM 👍.

**Comment by tsteur** [comment]
We'll release a new update shortly on iOS and then it'll be updated there as well.
