### ISSUE TITLE
iOS Dark Mode "Add Account" cannot read text when entering account details

### ISSUE THREAD

**Issue by Starker3** [matomo-org/matomo-mobile-2#5411]
Received a review on the Matomo Mobile App:
![Review Screenshot](https://user-images.githubusercontent.com/20905821/97243562-73462700-185b-11eb-822a-066d195817f5.jpg)
Translation: 
In dark mode, the text of the login form is white on white, there are many inconsistencies with dark mode activated within the app.

Bug does not occur on Android under the same circumstances

Screenshots of App on iOS with darkmode enabled in system settings:
"Add Account" Page with darkmode enabled:
![Screenshot 1](https://user-images.githubusercontent.com/20905821/97243773-eea7d880-185b-11eb-9b16-2186f53bb5af.jpg)
"Add Account" Page with the url/username/password filled in shows white text on white background
![Screenshot 2](https://user-images.githubusercontent.com/20905821/97243774-ef406f00-185b-11eb-832f-25a91869b997.jpg)
The accounts overview page with darkmode enabled:
![Screenshot 3](https://user-images.githubusercontent.com/20905821/97243776-efd90580-185b-11eb-8f3a-3affa33cd5a7.jpg)

**Comment by tsteur** [comment]
@Starker3 do you know if dark mode is something that can be configured/enabled per app?

**Comment by Starker3** [comment]
@tsteur We can set UIUserInterfaceStyle to Light in the Info.Plist
That will tell iOS to not turn on any of the dark mode settings for the app.

We can get more info about this here: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW44

**Comment by tsteur** [comment]
👍  created https://github.com/matomo-org/matomo-mobile-2/pull/5412 according to https://jasonified.com/forcing-titanium-apps-to-use-light-mode-in-ios-13-bc108462a865 but will still need to test it.

**Comment by tsteur** [comment]
Thanks @Starker3 this will be fixed in next release
