### ISSUE TITLE
No login possible with 2FA and matomo 4

### ISSUE THREAD

**Issue by pgampe** [matomo-org/matomo-mobile-2#5413]
After entering the 2FA code, I get asked again for a 2FA code. I can see that each time, the app creates a new auth token, so the authentication must have been successful.

current iOS version with Matomo 4

**Comment by tsteur** [comment]
@pgampe that's certainly not expected. Did you have this problem before with Matomo 3 as well? 

That it creates many auth tokens makes me think it somehow doesn't store the auth token on the device. Can you log in at all? Or it always just asks for the 2FA token again and again?

**Comment by tsteur** [comment]
Hi @pgampe I think I was able to reproduce this and might have a fix for it. I will release a new version for iOS (and Android) and it should hopefully be fixed in a few days.
