### ISSUE TITLE
Fix broken date selector in iOS

### ISSUE THREAD

**Issue by Starker3** [matomo-org/matomo-mobile-2#5415]
It seems a recent iOS software update has changed the date selector for the Matomo Mobile 2 app on iOS
![image](https://user-images.githubusercontent.com/20905821/100696006-6044ea80-33f7-11eb-8cea-e8aee0a9087b.png)

More information about the updated date selectors in iOS 14 can be found here: https://developer.apple.com/design/human-interface-guidelines/ios/controls/pickers/

**Comment by Starker3** [comment]
It seems the support for the new date selectors was added in September: https://github.com/appcelerator/titanium_mobile/pull/11977

**Comment by tsteur** [comment]
fyi spent an hour last night trying to fix it and couldn't figure it out. I tried all the new picker styles plus 30 other things and didn't get it working. Will need to check some other day again. Maybe some future titanium update will fix it
