### ISSUE TITLE
Matomo Mobile Android E-commerce Order

### ISSUE THREAD

**Issue by snoroozi** [matomo-org/matomo-mobile-2#5420]
Goals highlight yellow on the mobile app. Would be nice to see E-commerce orders highlighted in light green.

I currently have a goal on my order confirmation page, but this can trigger if a customer manually visits that page, and yes I have goal settings to fire once per goal.  But if a customer comes back to that page it fires again without e-commerce value.

So either highlight e-commerce orders in green (example) or make it possible in core to link e-commerce orders as a goal without setting a url.

**Comment by tsteur** [comment]
Thanks for the suggestion @snoroozi I've created a PR in https://github.com/matomo-org/matomo-mobile-2/pull/5421 and we're planning to merge this before the next release.

**Comment by snoroozi** [comment]
You'd need to come up with some solution when a visitor is both a goal and an E-commerce order. Maybe a green 10px left edge and then yellow?

**Comment by tsteur** [comment]
@snoroozi  we'd likely keep it simple as from a user point of view that might be hard to understand I suppose. Not sure how important it is to have it marked as both? Otherwise we might just mark them yellow as well (if that's not the case yet) or show some icon for orders (if that's not the case yet)

**Comment by snoroozi** [comment]
I was thinking an icon too

**Comment by tsteur** [comment]
This is done, will be included in next release

**Comment by snoroozi** [comment]
Thank you. Looks good on my Android
