### ISSUE TITLE
Incompatible with my Android 9 Phone

### ISSUE THREAD

**Issue by fekoch** [matomo-org/matomo-mobile-2#5438]
The app shows as incompatible with my Device:

- Model: SM-A530F
- Android-Version: 9

![Screenshot 1](https://user-images.githubusercontent.com/45557700/179725113-19f2d78a-4fcb-40e8-83d5-a8277fe2466d.jpg)

![Screenshot 2](https://user-images.githubusercontent.com/45557700/179725163-72d1efb8-f0e7-4aea-8f29-bb2db92fc4e6.jpg)

**Comment by tsteur** [comment]
Closing this one as a won't fix as the recent versions don't support Android 9 anymore. Older builds can be downloaded from https://matomo.org/faq/mobile-app/faq_16330/
