### ISSUE TITLE
Problem logging in via iPhone

### ISSUE THREAD

**Issue by adpablos** [matomo-org/matomo-mobile-2#5444]
Having the very last Matomo version installed

<img width="559" alt="CleanShot 2023-01-25 at 21 51 37@2x" src="https://user-images.githubusercontent.com/9111938/214747867-910ab55b-f157-479c-9d6a-f3bf4d178467.png">

The System summary is

<img width="542" alt="CleanShot 2023-01-25 at 21 51 18@2x" src="https://user-images.githubusercontent.com/9111938/214747804-1eab8cdf-c401-4fcf-b8e0-8135a5ab8ee5.png">

I am not able to log in via my iPhone.

<img width="254" alt="CleanShot 2023-01-25 at 21 52 23@2x" src="https://user-images.githubusercontent.com/9111938/214747953-879e35d5-dab3-4fda-b0f1-dbadc04c0671.png">

Having the following message

<img width="254" alt="CleanShot 2023-01-25 at 21 52 44@2x" src="https://user-images.githubusercontent.com/9111938/214748029-a0dd571d-388b-416e-840d-5e10a6885b8f.png">

When logging in via website with same url, user and password

<img width="560" alt="CleanShot 2023-01-25 at 21 53 24@2x" src="https://user-images.githubusercontent.com/9111938/214748086-44559774-dcf4-470b-99e2-659cb4b0227a.png">

I am perfectly able to access

<img width="560" alt="CleanShot 2023-01-25 at 21 53 42@2x" src="https://user-images.githubusercontent.com/9111938/214748118-37482c44-2367-46c8-ab5b-5e199c2f32ac.png">

I was able to see my information via my iPhone till few weeks ago when sudently I started having that error.

**Comment by rneil68** [comment]
Same issue here. No errors showing in server logs.

**Comment by adpablos** [comment]
Is there any news about this? Anybody working on it?

**Comment by tsteur** [comment]
@adpablos @rneil68 sorry I can't reproduce this one yet.

By any chance do you have any kind of special characters in your password? If so, do you mind sharing which ones?

It sounds like there is a server error happening meaning the error may be in Matomo rather than the mobile app.

**Comment by rneil68** [comment]
Mine has a !Sent from my iPhoneOn 5 Mar 2023, at 20:05, Thomas Steur ***@***.***> wrote:﻿
@adpablos @rneil68 sorry I can't reproduce this one yet.
By any chance do you have any kind of special characters in your password? If so, do you mind sharing which ones?
It sounds like there is a server error happening meaning the error may be in Matomo rather than the mobile app.

**Comment by adpablos** [comment]
I have 2 different users. One is admin and other is user. None of them is working.

For the regular user I just have a '.' as an special character.
For the admin one I have '*' and '!' characters.

**Comment by rneil68** [comment]
Just tried with a revised password without special characters -  error persists.Sent from my iPhoneOn 5 Mar 2023, at 23:31, Alex de Pablos ***@***.***> wrote:﻿
I have 2 different users. One is admin and other is user. None of them is working.
For the regular user I just have a '.' as an special character.
For the admin one I have '*' and '!' characters.

**Comment by tsteur** [comment]
Thanks @adpablos @rneil68 .

Is there any chance of you could send me an invite for thomas@matomo.org ? You could create a new site and give me "view" access to this new site so I wouldn't be able to see any actual data. This would allow me to troubleshoot the issue and see if it's an issue with the mobile app or Matomo itself.

**Comment by adpablos** [comment]
Done!

**Comment by tsteur** [comment]
Thanks for this @adpablos Very appreciated.

I've just checked. On Android it doesn't work either and I'm getting this error: `unexpected end of stream on com.android.ok http.address@17e9f0a0`. Below is what I'm finding on this.

The error message suggests that the response stream was ended abruptly, which could indicate a problem with the server or network.

There could be several reasons why this error might occur. Some of the common causes include:

* Server-side issues: The server might have encountered an error while processing the request and ended the response stream abruptly.
* Network issues: There could be issues with the network connection that caused the response to be interrupted or lost.
* Connection issues: The connection to the server might have been lost or interrupted during the request.

To troubleshoot this issue, you can try the following steps:

* Check the server logs: If you have access to the server, check the server logs to see if there were any errors or issues that might have caused the response to be interrupted.

In https://learn.microsoft.com/en-us/answers/questions/582274/why-do-i-keeo-getting-com-android-okhttp-address@5 it suggests there may be an issue with a server side "keep-alive" setting. I don't know how technical you are and if you have any control over these kind of things to look into anything there?

It's a very weird thing as it works nicely in the browser. There seems to be some sort of connection issue.

There may be a way to workaround this error in the app but I believe we may not have access to this level of control over how the HTTP request is sent. This is something we could check. --> Looking into this on https://titaniumsdk.com/api/titanium/network/httpclient.html#properties_waitsforconnectivity it doesn't look like we can do anything about it.

**Comment by adpablos** [comment]
Hey there!

I have been dealing with my hosting support service letting them know about
this.

This was their last response

Hello Alejandro,

I am able to replicate the issue on the Matomo app from the App Store.
However, I monitored the Apache and Nginx logs simultaneously and there are
no requests that reach our server.

I am afraid that there is not much that can be done on our end. The
application is accessible from any other web client. I would recommend
contacting the developers of the Matomo app and report the issue to them.
This appears to be a common issue as I notice that other users are also
reporting the same on your github thread, and there are some other threads
with the same issue as shown here for example:

https://forum.matomo.org/t/network-error-iphone-matomo-app/40399/3

Best Regards,

So, being like that.. I guess the ball is again under your roof…

Let me know if you can figure it out.

I am pretty sure should have been something related with some update, since
I was able to work with the app before.

Regards.

**Comment by tsteur** [comment]
FYI been doing lots of troubleshooting. It looks like when I update our user agent that it then works. The user agent that may be causing problems is `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1`. I still need to investigate further.

**Comment by tsteur** [comment]
FYI I generally have found the fix which is to udpate the user agent. Don't know if you can already configure something to allow our old user agent.
I have a fix prepared in https://github.com/matomo-org/matomo-mobile-2/pull/5447

The only problem I have currently is that the app crashes as soon as a request fails for any reason (like wrong password entered). I'm not sure if this is only in the simular or also behaviour on an actual phone. I haven't had such an issue before and don't have an iOS device myself.

This will require further investigation.

**Comment by adpablos** [comment]
I can not tell you either what happens right now in the app if you enter a
wrong pass… since the error I got is always the same specified in this
thread.

I saw your changes in the fix you opened were already merged with master
branch, right? That means it will be already solved with the next release?

**Comment by tsteur** [comment]
@adpablos this issue has been fixed and we've submitted the update for review. Once the update has been approved, the update will be rolled out over 7 days meaning it can take up to 10 days for you to receive the update. Although it could also be a lot sooner. 
Thanks for bringing the issue to our attention!

**Comment by adpablos** [comment]
Thank you for your work fixing this!

I will wait anxiously to have that updated.
